spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
###zipkin 相关
  zipkin:
    base-url: http://localhost:9411
    service:
      name: bc-ebiz-user
  sleuth:
    #监控开关
    enabled: true
    #采样率
    sampler:
      percentage: 1
server:
  port: 8881
  context-path: /
  tomcat:
    uri-encoding: utf-8
bc:
  data:
    mybatis:
      base-package: com.bc.ebiz.user.persist
      type-aliases-package: com.bc.ebiz.user.persist.entity
      identity: MYSQL
      mapper-locations: classpath*:/mapper/**/*.xml
      check-config-location: false
      not-empty: false

#      mappers: com.mamahao.data.framework.mybatis.bean.IMapper
      mappers: org.spring.data.framework.mybatis.bean.IMapper
      config: mybatis-config.xml
eureka:
  instance:
    metadata-map:
      cluster: BC-EBIZ-USER


